import type { Shelter, NewsItem } from "./types"

export const mockShelters: Shelter[] = [
  {
    id: "1",
    name: "Centro de Esperanza",
    address: "1501 Imperial Ave, San Diego, CA 92101",
    lat: 32.7157,
    lng: -117.1611,
    phone: "(619) 123-4567",
    capacity: 50,
    availableBeds: 12,
    services: ["Comida", "Ducha", "Ropa", "Asesoría"],
    hours: "24 horas",
    description: "Refugio con servicios completos, comidas tres veces al día",
  },
  {
    id: "2",
    name: "Refugio San José",
    address: "3350 E St, San Diego, CA 92102",
    lat: 32.7089,
    lng: -117.1289,
    phone: "(619) 234-5678",
    capacity: 30,
    availableBeds: 5,
    services: ["Comida", "Ducha", "Médico"],
    hours: "6:00 PM - 8:00 AM",
    description: "Refugio nocturno con atención médica básica",
  },
  {
    id: "3",
    name: "Casa de Paz",
    address: "2020 Newton Ave, San Diego, CA 92113",
    lat: 32.6981,
    lng: -117.1342,
    phone: "(619) 345-6789",
    capacity: 40,
    availableBeds: 18,
    services: ["Comida", "Ducha", "Ropa", "Trabajo Social"],
    hours: "24 horas",
    description: "Refugio familiar con programas de reinserción",
  },
  {
    id: "4",
    name: "Albergue Nueva Vida",
    address: "252 16th St, San Diego, CA 92101",
    lat: 32.7098,
    lng: -117.1489,
    phone: "(619) 456-7890",
    capacity: 25,
    availableBeds: 8,
    services: ["Comida", "Ducha", "Asesoría Legal"],
    hours: "5:00 PM - 9:00 AM",
    description: "Refugio con apoyo legal y documentación",
  },
  {
    id: "5",
    name: "Centro Comunitario El Buen Samaritano",
    address: "1501 30th St, San Diego, CA 92102",
    lat: 32.7245,
    lng: -117.1298,
    phone: "(619) 567-8901",
    capacity: 60,
    availableBeds: 22,
    services: ["Comida", "Ducha", "Ropa", "Médico", "Dental"],
    hours: "24 horas",
    description: "Centro completo con servicios médicos y dentales",
  },
  {
    id: "6",
    name: "Refugio del Norte",
    address: "4002 Fairmount Ave, San Diego, CA 92105",
    lat: 32.7456,
    lng: -117.1089,
    phone: "(619) 678-9012",
    capacity: 35,
    availableBeds: 15,
    services: ["Comida", "Ducha", "Ropa"],
    hours: "24 horas",
    description: "Refugio comunitario con ambiente familiar",
  },
]

export const mockNews: NewsItem[] = [
  {
    id: "1",
    title: "Nuevo programa de empleo disponible",
    date: "2025-01-15",
    category: "resource",
    content:
      "Se abrió un nuevo programa de capacitación laboral con oportunidades de empleo inmediato en construcción y servicios.",
  },
  {
    id: "2",
    title: "Distribución de ropa de invierno",
    date: "2025-01-14",
    category: "event",
    content: "Este sábado habrá distribución gratuita de abrigos y mantas en el Centro de Esperanza de 10 AM a 4 PM.",
  },
  {
    id: "3",
    title: "Alerta: Temperaturas bajas esta semana",
    date: "2025-01-13",
    category: "alert",
    content: "Se esperan temperaturas bajo cero. Todos los refugios extenderán horarios y capacidad de emergencia.",
  },
  {
    id: "4",
    title: "Clínica dental gratuita",
    date: "2025-01-12",
    category: "resource",
    content: "Servicios dentales gratuitos disponibles en Casa de Paz todos los martes de 9 AM a 3 PM.",
  },
]
